### PR TITLE
Give possibility to mask zero balances

### PR DESCRIPTION
**Pull request by NandyBa**
## Content :
- This feature gives to the user the possibility to show / hide zero balances.
- The selection can be made on the app's settings

### CODE REVIEW

**Review by thegodfatherbeeearth — COMMENTED** [review]
Looks great! A few comments:

1. It looks like the setting currently is not preserved between app runs, right? It should be!
2. I would put the setting to "On" by default. Mainly to not confuse already existing app's users.
3. Currently the circle on the switch is green, but I would make it of some Aave-related color
image

**Comment by NandyBa** [comment]
1. I've currently implemented a state version. I tried using `supabase`, but it wasn't successful (first try with this lib)
2. I've been contemplating whether to implement it as the default. I decided to follow the Aave website's approach, which masks zero balances by default. However, if you believe the alternative setting is better, I'm open to implementing it.

**Comment by thegodfatherbeeearth** [comment]
> I've been contemplating whether to implement it as the default. I decided to follow the Aave website's approach, which masks zero balances by default. However, if you believe the alternative setting is better, I'm open to implementing it.

Ah, having it same as Aave's web app makes sense!

> I've currently implemented a state version. I tried using supabase, but it wasn't successful (first try with this lib)

Doesn't have to be stored in supabase. Can be just a local setting. But it should be stored and preserved somehow.

**Comment by NandyBa** [comment]
Settings updated

**Comment by NandyBa** [comment]
> > I've currently implemented a state version. I tried using supabase, but it wasn't successful (first try with this lib)
> 
> Doesn't have to be stored in supabase. Can be just a local setting. But it should be stored and preserved somehow.

App updated, the balance settings are now stored locally.
Users will keep their settings if they close the app and try to  re-open the app.

**Comment by NandyBa** [comment]
> 3. Currently the circle on the switch is green, but I would make it of some Aave-related color
> 
> image

Oh it's seems to appear green on Android only caused by default switch colors on this platform
### Current look on iOS:
#### Disabled
Capture d’écran 2023-09-24 à 21 05 28

#### Enabled
Capture d’écran 2023-09-24 à 21 05 32

#### Tasks

I will update the component to get the same aspect on both platform (update: done ✅)

**Comment by thegodfatherbeeearth** [comment]
Looks great!! The setting works and persists across app runs. Great contribution!

**Pull request merged**
